################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../TFLM/tensorflow/lite/micro/kernels/activations.cc \
../TFLM/tensorflow/lite/micro/kernels/activations_common.cc \
../TFLM/tensorflow/lite/micro/kernels/add_common.cc \
../TFLM/tensorflow/lite/micro/kernels/add_n.cc \
../TFLM/tensorflow/lite/micro/kernels/arg_min_max.cc \
../TFLM/tensorflow/lite/micro/kernels/assign_variable.cc \
../TFLM/tensorflow/lite/micro/kernels/batch_matmul_common.cc \
../TFLM/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../TFLM/tensorflow/lite/micro/kernels/broadcast_args.cc \
../TFLM/tensorflow/lite/micro/kernels/broadcast_to.cc \
../TFLM/tensorflow/lite/micro/kernels/call_once.cc \
../TFLM/tensorflow/lite/micro/kernels/cast.cc \
../TFLM/tensorflow/lite/micro/kernels/ceil.cc \
../TFLM/tensorflow/lite/micro/kernels/circular_buffer.cc \
../TFLM/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../TFLM/tensorflow/lite/micro/kernels/comparisons.cc \
../TFLM/tensorflow/lite/micro/kernels/concatenation.cc \
../TFLM/tensorflow/lite/micro/kernels/conv_common.cc \
../TFLM/tensorflow/lite/micro/kernels/cumsum.cc \
../TFLM/tensorflow/lite/micro/kernels/decompress.cc \
../TFLM/tensorflow/lite/micro/kernels/decompress_common.cc \
../TFLM/tensorflow/lite/micro/kernels/depth_to_space.cc \
../TFLM/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../TFLM/tensorflow/lite/micro/kernels/dequantize.cc \
../TFLM/tensorflow/lite/micro/kernels/dequantize_common.cc \
../TFLM/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../TFLM/tensorflow/lite/micro/kernels/div.cc \
../TFLM/tensorflow/lite/micro/kernels/elementwise.cc \
../TFLM/tensorflow/lite/micro/kernels/elu.cc \
../TFLM/tensorflow/lite/micro/kernels/embedding_lookup.cc \
../TFLM/tensorflow/lite/micro/kernels/ethosu.cc \
../TFLM/tensorflow/lite/micro/kernels/exp.cc \
../TFLM/tensorflow/lite/micro/kernels/expand_dims.cc \
../TFLM/tensorflow/lite/micro/kernels/fill.cc \
../TFLM/tensorflow/lite/micro/kernels/floor.cc \
../TFLM/tensorflow/lite/micro/kernels/floor_div.cc \
../TFLM/tensorflow/lite/micro/kernels/floor_mod.cc \
../TFLM/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../TFLM/tensorflow/lite/micro/kernels/gather.cc \
../TFLM/tensorflow/lite/micro/kernels/gather_nd.cc \
../TFLM/tensorflow/lite/micro/kernels/hard_swish.cc \
../TFLM/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../TFLM/tensorflow/lite/micro/kernels/if.cc \
../TFLM/tensorflow/lite/micro/kernels/kernel_runner.cc \
../TFLM/tensorflow/lite/micro/kernels/kernel_util.cc \
../TFLM/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../TFLM/tensorflow/lite/micro/kernels/l2norm.cc \
../TFLM/tensorflow/lite/micro/kernels/leaky_relu.cc \
../TFLM/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../TFLM/tensorflow/lite/micro/kernels/log_softmax.cc \
../TFLM/tensorflow/lite/micro/kernels/logical.cc \
../TFLM/tensorflow/lite/micro/kernels/logical_common.cc \
../TFLM/tensorflow/lite/micro/kernels/logistic.cc \
../TFLM/tensorflow/lite/micro/kernels/logistic_common.cc \
../TFLM/tensorflow/lite/micro/kernels/lstm_eval.cc \
../TFLM/tensorflow/lite/micro/kernels/lstm_eval_common.cc \
../TFLM/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../TFLM/tensorflow/lite/micro/kernels/mirror_pad.cc \
../TFLM/tensorflow/lite/micro/kernels/mul_common.cc \
../TFLM/tensorflow/lite/micro/kernels/neg.cc \
../TFLM/tensorflow/lite/micro/kernels/pack.cc \
../TFLM/tensorflow/lite/micro/kernels/pad_common.cc \
../TFLM/tensorflow/lite/micro/kernels/pooling_common.cc \
../TFLM/tensorflow/lite/micro/kernels/prelu.cc \
../TFLM/tensorflow/lite/micro/kernels/prelu_common.cc \
../TFLM/tensorflow/lite/micro/kernels/quantize.cc \
../TFLM/tensorflow/lite/micro/kernels/quantize_common.cc \
../TFLM/tensorflow/lite/micro/kernels/read_variable.cc \
../TFLM/tensorflow/lite/micro/kernels/reduce.cc \
../TFLM/tensorflow/lite/micro/kernels/reduce_common.cc \
../TFLM/tensorflow/lite/micro/kernels/reshape.cc \
../TFLM/tensorflow/lite/micro/kernels/reshape_common.cc \
../TFLM/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../TFLM/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../TFLM/tensorflow/lite/micro/kernels/round.cc \
../TFLM/tensorflow/lite/micro/kernels/select.cc \
../TFLM/tensorflow/lite/micro/kernels/shape.cc \
../TFLM/tensorflow/lite/micro/kernels/slice.cc \
../TFLM/tensorflow/lite/micro/kernels/softmax_common.cc \
../TFLM/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../TFLM/tensorflow/lite/micro/kernels/space_to_depth.cc \
../TFLM/tensorflow/lite/micro/kernels/split.cc \
../TFLM/tensorflow/lite/micro/kernels/split_v.cc \
../TFLM/tensorflow/lite/micro/kernels/squared_difference.cc \
../TFLM/tensorflow/lite/micro/kernels/squeeze.cc \
../TFLM/tensorflow/lite/micro/kernels/strided_slice.cc \
../TFLM/tensorflow/lite/micro/kernels/strided_slice_common.cc \
../TFLM/tensorflow/lite/micro/kernels/sub.cc \
../TFLM/tensorflow/lite/micro/kernels/sub_common.cc \
../TFLM/tensorflow/lite/micro/kernels/svdf_common.cc \
../TFLM/tensorflow/lite/micro/kernels/tanh.cc \
../TFLM/tensorflow/lite/micro/kernels/transpose_common.cc \
../TFLM/tensorflow/lite/micro/kernels/unpack.cc \
../TFLM/tensorflow/lite/micro/kernels/var_handle.cc \
../TFLM/tensorflow/lite/micro/kernels/while.cc \
../TFLM/tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./TFLM/tensorflow/lite/micro/kernels/activations.d \
./TFLM/tensorflow/lite/micro/kernels/activations_common.d \
./TFLM/tensorflow/lite/micro/kernels/add_common.d \
./TFLM/tensorflow/lite/micro/kernels/add_n.d \
./TFLM/tensorflow/lite/micro/kernels/arg_min_max.d \
./TFLM/tensorflow/lite/micro/kernels/assign_variable.d \
./TFLM/tensorflow/lite/micro/kernels/batch_matmul_common.d \
./TFLM/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./TFLM/tensorflow/lite/micro/kernels/broadcast_args.d \
./TFLM/tensorflow/lite/micro/kernels/broadcast_to.d \
./TFLM/tensorflow/lite/micro/kernels/call_once.d \
./TFLM/tensorflow/lite/micro/kernels/cast.d \
./TFLM/tensorflow/lite/micro/kernels/ceil.d \
./TFLM/tensorflow/lite/micro/kernels/circular_buffer.d \
./TFLM/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./TFLM/tensorflow/lite/micro/kernels/comparisons.d \
./TFLM/tensorflow/lite/micro/kernels/concatenation.d \
./TFLM/tensorflow/lite/micro/kernels/conv_common.d \
./TFLM/tensorflow/lite/micro/kernels/cumsum.d \
./TFLM/tensorflow/lite/micro/kernels/decompress.d \
./TFLM/tensorflow/lite/micro/kernels/decompress_common.d \
./TFLM/tensorflow/lite/micro/kernels/depth_to_space.d \
./TFLM/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./TFLM/tensorflow/lite/micro/kernels/dequantize.d \
./TFLM/tensorflow/lite/micro/kernels/dequantize_common.d \
./TFLM/tensorflow/lite/micro/kernels/detection_postprocess.d \
./TFLM/tensorflow/lite/micro/kernels/div.d \
./TFLM/tensorflow/lite/micro/kernels/elementwise.d \
./TFLM/tensorflow/lite/micro/kernels/elu.d \
./TFLM/tensorflow/lite/micro/kernels/embedding_lookup.d \
./TFLM/tensorflow/lite/micro/kernels/ethosu.d \
./TFLM/tensorflow/lite/micro/kernels/exp.d \
./TFLM/tensorflow/lite/micro/kernels/expand_dims.d \
./TFLM/tensorflow/lite/micro/kernels/fill.d \
./TFLM/tensorflow/lite/micro/kernels/floor.d \
./TFLM/tensorflow/lite/micro/kernels/floor_div.d \
./TFLM/tensorflow/lite/micro/kernels/floor_mod.d \
./TFLM/tensorflow/lite/micro/kernels/fully_connected_common.d \
./TFLM/tensorflow/lite/micro/kernels/gather.d \
./TFLM/tensorflow/lite/micro/kernels/gather_nd.d \
./TFLM/tensorflow/lite/micro/kernels/hard_swish.d \
./TFLM/tensorflow/lite/micro/kernels/hard_swish_common.d \
./TFLM/tensorflow/lite/micro/kernels/if.d \
./TFLM/tensorflow/lite/micro/kernels/kernel_runner.d \
./TFLM/tensorflow/lite/micro/kernels/kernel_util.d \
./TFLM/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./TFLM/tensorflow/lite/micro/kernels/l2norm.d \
./TFLM/tensorflow/lite/micro/kernels/leaky_relu.d \
./TFLM/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./TFLM/tensorflow/lite/micro/kernels/log_softmax.d \
./TFLM/tensorflow/lite/micro/kernels/logical.d \
./TFLM/tensorflow/lite/micro/kernels/logical_common.d \
./TFLM/tensorflow/lite/micro/kernels/logistic.d \
./TFLM/tensorflow/lite/micro/kernels/logistic_common.d \
./TFLM/tensorflow/lite/micro/kernels/lstm_eval.d \
./TFLM/tensorflow/lite/micro/kernels/lstm_eval_common.d \
./TFLM/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./TFLM/tensorflow/lite/micro/kernels/mirror_pad.d \
./TFLM/tensorflow/lite/micro/kernels/mul_common.d \
./TFLM/tensorflow/lite/micro/kernels/neg.d \
./TFLM/tensorflow/lite/micro/kernels/pack.d \
./TFLM/tensorflow/lite/micro/kernels/pad_common.d \
./TFLM/tensorflow/lite/micro/kernels/pooling_common.d \
./TFLM/tensorflow/lite/micro/kernels/prelu.d \
./TFLM/tensorflow/lite/micro/kernels/prelu_common.d \
./TFLM/tensorflow/lite/micro/kernels/quantize.d \
./TFLM/tensorflow/lite/micro/kernels/quantize_common.d \
./TFLM/tensorflow/lite/micro/kernels/read_variable.d \
./TFLM/tensorflow/lite/micro/kernels/reduce.d \
./TFLM/tensorflow/lite/micro/kernels/reduce_common.d \
./TFLM/tensorflow/lite/micro/kernels/reshape.d \
./TFLM/tensorflow/lite/micro/kernels/reshape_common.d \
./TFLM/tensorflow/lite/micro/kernels/resize_bilinear.d \
./TFLM/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./TFLM/tensorflow/lite/micro/kernels/round.d \
./TFLM/tensorflow/lite/micro/kernels/select.d \
./TFLM/tensorflow/lite/micro/kernels/shape.d \
./TFLM/tensorflow/lite/micro/kernels/slice.d \
./TFLM/tensorflow/lite/micro/kernels/softmax_common.d \
./TFLM/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./TFLM/tensorflow/lite/micro/kernels/space_to_depth.d \
./TFLM/tensorflow/lite/micro/kernels/split.d \
./TFLM/tensorflow/lite/micro/kernels/split_v.d \
./TFLM/tensorflow/lite/micro/kernels/squared_difference.d \
./TFLM/tensorflow/lite/micro/kernels/squeeze.d \
./TFLM/tensorflow/lite/micro/kernels/strided_slice.d \
./TFLM/tensorflow/lite/micro/kernels/strided_slice_common.d \
./TFLM/tensorflow/lite/micro/kernels/sub.d \
./TFLM/tensorflow/lite/micro/kernels/sub_common.d \
./TFLM/tensorflow/lite/micro/kernels/svdf_common.d \
./TFLM/tensorflow/lite/micro/kernels/tanh.d \
./TFLM/tensorflow/lite/micro/kernels/transpose_common.d \
./TFLM/tensorflow/lite/micro/kernels/unpack.d \
./TFLM/tensorflow/lite/micro/kernels/var_handle.d \
./TFLM/tensorflow/lite/micro/kernels/while.d \
./TFLM/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./TFLM/tensorflow/lite/micro/kernels/activations.o \
./TFLM/tensorflow/lite/micro/kernels/activations_common.o \
./TFLM/tensorflow/lite/micro/kernels/add_common.o \
./TFLM/tensorflow/lite/micro/kernels/add_n.o \
./TFLM/tensorflow/lite/micro/kernels/arg_min_max.o \
./TFLM/tensorflow/lite/micro/kernels/assign_variable.o \
./TFLM/tensorflow/lite/micro/kernels/batch_matmul_common.o \
./TFLM/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./TFLM/tensorflow/lite/micro/kernels/broadcast_args.o \
./TFLM/tensorflow/lite/micro/kernels/broadcast_to.o \
./TFLM/tensorflow/lite/micro/kernels/call_once.o \
./TFLM/tensorflow/lite/micro/kernels/cast.o \
./TFLM/tensorflow/lite/micro/kernels/ceil.o \
./TFLM/tensorflow/lite/micro/kernels/circular_buffer.o \
./TFLM/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./TFLM/tensorflow/lite/micro/kernels/comparisons.o \
./TFLM/tensorflow/lite/micro/kernels/concatenation.o \
./TFLM/tensorflow/lite/micro/kernels/conv_common.o \
./TFLM/tensorflow/lite/micro/kernels/cumsum.o \
./TFLM/tensorflow/lite/micro/kernels/decompress.o \
./TFLM/tensorflow/lite/micro/kernels/decompress_common.o \
./TFLM/tensorflow/lite/micro/kernels/depth_to_space.o \
./TFLM/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./TFLM/tensorflow/lite/micro/kernels/dequantize.o \
./TFLM/tensorflow/lite/micro/kernels/dequantize_common.o \
./TFLM/tensorflow/lite/micro/kernels/detection_postprocess.o \
./TFLM/tensorflow/lite/micro/kernels/div.o \
./TFLM/tensorflow/lite/micro/kernels/elementwise.o \
./TFLM/tensorflow/lite/micro/kernels/elu.o \
./TFLM/tensorflow/lite/micro/kernels/embedding_lookup.o \
./TFLM/tensorflow/lite/micro/kernels/ethosu.o \
./TFLM/tensorflow/lite/micro/kernels/exp.o \
./TFLM/tensorflow/lite/micro/kernels/expand_dims.o \
./TFLM/tensorflow/lite/micro/kernels/fill.o \
./TFLM/tensorflow/lite/micro/kernels/floor.o \
./TFLM/tensorflow/lite/micro/kernels/floor_div.o \
./TFLM/tensorflow/lite/micro/kernels/floor_mod.o \
./TFLM/tensorflow/lite/micro/kernels/fully_connected_common.o \
./TFLM/tensorflow/lite/micro/kernels/gather.o \
./TFLM/tensorflow/lite/micro/kernels/gather_nd.o \
./TFLM/tensorflow/lite/micro/kernels/hard_swish.o \
./TFLM/tensorflow/lite/micro/kernels/hard_swish_common.o \
./TFLM/tensorflow/lite/micro/kernels/if.o \
./TFLM/tensorflow/lite/micro/kernels/kernel_runner.o \
./TFLM/tensorflow/lite/micro/kernels/kernel_util.o \
./TFLM/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./TFLM/tensorflow/lite/micro/kernels/l2norm.o \
./TFLM/tensorflow/lite/micro/kernels/leaky_relu.o \
./TFLM/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./TFLM/tensorflow/lite/micro/kernels/log_softmax.o \
./TFLM/tensorflow/lite/micro/kernels/logical.o \
./TFLM/tensorflow/lite/micro/kernels/logical_common.o \
./TFLM/tensorflow/lite/micro/kernels/logistic.o \
./TFLM/tensorflow/lite/micro/kernels/logistic_common.o \
./TFLM/tensorflow/lite/micro/kernels/lstm_eval.o \
./TFLM/tensorflow/lite/micro/kernels/lstm_eval_common.o \
./TFLM/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./TFLM/tensorflow/lite/micro/kernels/mirror_pad.o \
./TFLM/tensorflow/lite/micro/kernels/mul_common.o \
./TFLM/tensorflow/lite/micro/kernels/neg.o \
./TFLM/tensorflow/lite/micro/kernels/pack.o \
./TFLM/tensorflow/lite/micro/kernels/pad_common.o \
./TFLM/tensorflow/lite/micro/kernels/pooling_common.o \
./TFLM/tensorflow/lite/micro/kernels/prelu.o \
./TFLM/tensorflow/lite/micro/kernels/prelu_common.o \
./TFLM/tensorflow/lite/micro/kernels/quantize.o \
./TFLM/tensorflow/lite/micro/kernels/quantize_common.o \
./TFLM/tensorflow/lite/micro/kernels/read_variable.o \
./TFLM/tensorflow/lite/micro/kernels/reduce.o \
./TFLM/tensorflow/lite/micro/kernels/reduce_common.o \
./TFLM/tensorflow/lite/micro/kernels/reshape.o \
./TFLM/tensorflow/lite/micro/kernels/reshape_common.o \
./TFLM/tensorflow/lite/micro/kernels/resize_bilinear.o \
./TFLM/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./TFLM/tensorflow/lite/micro/kernels/round.o \
./TFLM/tensorflow/lite/micro/kernels/select.o \
./TFLM/tensorflow/lite/micro/kernels/shape.o \
./TFLM/tensorflow/lite/micro/kernels/slice.o \
./TFLM/tensorflow/lite/micro/kernels/softmax_common.o \
./TFLM/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./TFLM/tensorflow/lite/micro/kernels/space_to_depth.o \
./TFLM/tensorflow/lite/micro/kernels/split.o \
./TFLM/tensorflow/lite/micro/kernels/split_v.o \
./TFLM/tensorflow/lite/micro/kernels/squared_difference.o \
./TFLM/tensorflow/lite/micro/kernels/squeeze.o \
./TFLM/tensorflow/lite/micro/kernels/strided_slice.o \
./TFLM/tensorflow/lite/micro/kernels/strided_slice_common.o \
./TFLM/tensorflow/lite/micro/kernels/sub.o \
./TFLM/tensorflow/lite/micro/kernels/sub_common.o \
./TFLM/tensorflow/lite/micro/kernels/svdf_common.o \
./TFLM/tensorflow/lite/micro/kernels/tanh.o \
./TFLM/tensorflow/lite/micro/kernels/transpose_common.o \
./TFLM/tensorflow/lite/micro/kernels/unpack.o \
./TFLM/tensorflow/lite/micro/kernels/var_handle.o \
./TFLM/tensorflow/lite/micro/kernels/while.o \
./TFLM/tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
TFLM/tensorflow/lite/micro/kernels/%.o TFLM/tensorflow/lite/micro/kernels/%.su TFLM/tensorflow/lite/micro/kernels/%.cyclo: ../TFLM/tensorflow/lite/micro/kernels/%.cc TFLM/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++17 -g3 -DDEBUG -D__USE_CMSIS -DSTM32H743xx -DCMSIS_OPTIMIZATION_LEVEL -DCMSIS_NN -DTFT96 -DUSE_HAL_DRIVER -DSTM32 -DSTM32H7SINGLE -DSTM32H7 -DSTM32H743VITx -c -I../Inc -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/Drivers/BSP/ST7735" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/Drivers/BSP/Camera" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/Drivers/CMSIS/Include" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/Drivers/STM32H7xx_HAL_Driver/Inc" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/Drivers/CMSIS/Device/ST/STM32H7xx/Include" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/TFLM/third_party" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/TFLM/third_party/kissfft" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/TFLM/third_party/gemmlowp" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/TFLM/third_party/ruy" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/TFLM/third_party/flatbuffers/include" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/TFLM/third_party/cmsis_nn/Include" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/TFLM/third_party/cmsis_nn" -I"C:/Users/jashe/Documents/github/BareMetalAI_One/thread/stm32h743/TFLM" -O3 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-TFLM-2f-tensorflow-2f-lite-2f-micro-2f-kernels

clean-TFLM-2f-tensorflow-2f-lite-2f-micro-2f-kernels:
	-$(RM) ./TFLM/tensorflow/lite/micro/kernels/activations.cyclo ./TFLM/tensorflow/lite/micro/kernels/activations.d ./TFLM/tensorflow/lite/micro/kernels/activations.o ./TFLM/tensorflow/lite/micro/kernels/activations.su ./TFLM/tensorflow/lite/micro/kernels/activations_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/activations_common.d ./TFLM/tensorflow/lite/micro/kernels/activations_common.o ./TFLM/tensorflow/lite/micro/kernels/activations_common.su ./TFLM/tensorflow/lite/micro/kernels/add_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/add_common.d ./TFLM/tensorflow/lite/micro/kernels/add_common.o ./TFLM/tensorflow/lite/micro/kernels/add_common.su ./TFLM/tensorflow/lite/micro/kernels/add_n.cyclo ./TFLM/tensorflow/lite/micro/kernels/add_n.d ./TFLM/tensorflow/lite/micro/kernels/add_n.o ./TFLM/tensorflow/lite/micro/kernels/add_n.su ./TFLM/tensorflow/lite/micro/kernels/arg_min_max.cyclo ./TFLM/tensorflow/lite/micro/kernels/arg_min_max.d ./TFLM/tensorflow/lite/micro/kernels/arg_min_max.o ./TFLM/tensorflow/lite/micro/kernels/arg_min_max.su ./TFLM/tensorflow/lite/micro/kernels/assign_variable.cyclo ./TFLM/tensorflow/lite/micro/kernels/assign_variable.d ./TFLM/tensorflow/lite/micro/kernels/assign_variable.o ./TFLM/tensorflow/lite/micro/kernels/assign_variable.su ./TFLM/tensorflow/lite/micro/kernels/batch_matmul_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/batch_matmul_common.d ./TFLM/tensorflow/lite/micro/kernels/batch_matmul_common.o ./TFLM/tensorflow/lite/micro/kernels/batch_matmul_common.su ./TFLM/tensorflow/lite/micro/kernels/batch_to_space_nd.cyclo ./TFLM/tensorflow/lite/micro/kernels/batch_to_space_nd.d ./TFLM/tensorflow/lite/micro/kernels/batch_to_space_nd.o ./TFLM/tensorflow/lite/micro/kernels/batch_to_space_nd.su ./TFLM/tensorflow/lite/micro/kernels/broadcast_args.cyclo ./TFLM/tensorflow/lite/micro/kernels/broadcast_args.d ./TFLM/tensorflow/lite/micro/kernels/broadcast_args.o ./TFLM/tensorflow/lite/micro/kernels/broadcast_args.su ./TFLM/tensorflow/lite/micro/kernels/broadcast_to.cyclo ./TFLM/tensorflow/lite/micro/kernels/broadcast_to.d ./TFLM/tensorflow/lite/micro/kernels/broadcast_to.o ./TFLM/tensorflow/lite/micro/kernels/broadcast_to.su ./TFLM/tensorflow/lite/micro/kernels/call_once.cyclo ./TFLM/tensorflow/lite/micro/kernels/call_once.d ./TFLM/tensorflow/lite/micro/kernels/call_once.o ./TFLM/tensorflow/lite/micro/kernels/call_once.su ./TFLM/tensorflow/lite/micro/kernels/cast.cyclo ./TFLM/tensorflow/lite/micro/kernels/cast.d ./TFLM/tensorflow/lite/micro/kernels/cast.o ./TFLM/tensorflow/lite/micro/kernels/cast.su ./TFLM/tensorflow/lite/micro/kernels/ceil.cyclo ./TFLM/tensorflow/lite/micro/kernels/ceil.d ./TFLM/tensorflow/lite/micro/kernels/ceil.o ./TFLM/tensorflow/lite/micro/kernels/ceil.su ./TFLM/tensorflow/lite/micro/kernels/circular_buffer.cyclo ./TFLM/tensorflow/lite/micro/kernels/circular_buffer.d ./TFLM/tensorflow/lite/micro/kernels/circular_buffer.o ./TFLM/tensorflow/lite/micro/kernels/circular_buffer.su ./TFLM/tensorflow/lite/micro/kernels/circular_buffer_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/circular_buffer_common.d ./TFLM/tensorflow/lite/micro/kernels/circular_buffer_common.o ./TFLM/tensorflow/lite/micro/kernels/circular_buffer_common.su ./TFLM/tensorflow/lite/micro/kernels/comparisons.cyclo ./TFLM/tensorflow/lite/micro/kernels/comparisons.d ./TFLM/tensorflow/lite/micro/kernels/comparisons.o ./TFLM/tensorflow/lite/micro/kernels/comparisons.su ./TFLM/tensorflow/lite/micro/kernels/concatenation.cyclo ./TFLM/tensorflow/lite/micro/kernels/concatenation.d ./TFLM/tensorflow/lite/micro/kernels/concatenation.o ./TFLM/tensorflow/lite/micro/kernels/concatenation.su ./TFLM/tensorflow/lite/micro/kernels/conv_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/conv_common.d ./TFLM/tensorflow/lite/micro/kernels/conv_common.o ./TFLM/tensorflow/lite/micro/kernels/conv_common.su ./TFLM/tensorflow/lite/micro/kernels/cumsum.cyclo ./TFLM/tensorflow/lite/micro/kernels/cumsum.d ./TFLM/tensorflow/lite/micro/kernels/cumsum.o ./TFLM/tensorflow/lite/micro/kernels/cumsum.su ./TFLM/tensorflow/lite/micro/kernels/decompress.cyclo ./TFLM/tensorflow/lite/micro/kernels/decompress.d ./TFLM/tensorflow/lite/micro/kernels/decompress.o ./TFLM/tensorflow/lite/micro/kernels/decompress.su ./TFLM/tensorflow/lite/micro/kernels/decompress_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/decompress_common.d ./TFLM/tensorflow/lite/micro/kernels/decompress_common.o ./TFLM/tensorflow/lite/micro/kernels/decompress_common.su ./TFLM/tensorflow/lite/micro/kernels/depth_to_space.cyclo ./TFLM/tensorflow/lite/micro/kernels/depth_to_space.d ./TFLM/tensorflow/lite/micro/kernels/depth_to_space.o ./TFLM/tensorflow/lite/micro/kernels/depth_to_space.su ./TFLM/tensorflow/lite/micro/kernels/depthwise_conv_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/depthwise_conv_common.d ./TFLM/tensorflow/lite/micro/kernels/depthwise_conv_common.o ./TFLM/tensorflow/lite/micro/kernels/depthwise_conv_common.su ./TFLM/tensorflow/lite/micro/kernels/dequantize.cyclo ./TFLM/tensorflow/lite/micro/kernels/dequantize.d ./TFLM/tensorflow/lite/micro/kernels/dequantize.o ./TFLM/tensorflow/lite/micro/kernels/dequantize.su ./TFLM/tensorflow/lite/micro/kernels/dequantize_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/dequantize_common.d ./TFLM/tensorflow/lite/micro/kernels/dequantize_common.o ./TFLM/tensorflow/lite/micro/kernels/dequantize_common.su ./TFLM/tensorflow/lite/micro/kernels/detection_postprocess.cyclo ./TFLM/tensorflow/lite/micro/kernels/detection_postprocess.d ./TFLM/tensorflow/lite/micro/kernels/detection_postprocess.o ./TFLM/tensorflow/lite/micro/kernels/detection_postprocess.su ./TFLM/tensorflow/lite/micro/kernels/div.cyclo ./TFLM/tensorflow/lite/micro/kernels/div.d ./TFLM/tensorflow/lite/micro/kernels/div.o ./TFLM/tensorflow/lite/micro/kernels/div.su ./TFLM/tensorflow/lite/micro/kernels/elementwise.cyclo ./TFLM/tensorflow/lite/micro/kernels/elementwise.d ./TFLM/tensorflow/lite/micro/kernels/elementwise.o
	-$(RM) ./TFLM/tensorflow/lite/micro/kernels/elementwise.su ./TFLM/tensorflow/lite/micro/kernels/elu.cyclo ./TFLM/tensorflow/lite/micro/kernels/elu.d ./TFLM/tensorflow/lite/micro/kernels/elu.o ./TFLM/tensorflow/lite/micro/kernels/elu.su ./TFLM/tensorflow/lite/micro/kernels/embedding_lookup.cyclo ./TFLM/tensorflow/lite/micro/kernels/embedding_lookup.d ./TFLM/tensorflow/lite/micro/kernels/embedding_lookup.o ./TFLM/tensorflow/lite/micro/kernels/embedding_lookup.su ./TFLM/tensorflow/lite/micro/kernels/ethosu.cyclo ./TFLM/tensorflow/lite/micro/kernels/ethosu.d ./TFLM/tensorflow/lite/micro/kernels/ethosu.o ./TFLM/tensorflow/lite/micro/kernels/ethosu.su ./TFLM/tensorflow/lite/micro/kernels/exp.cyclo ./TFLM/tensorflow/lite/micro/kernels/exp.d ./TFLM/tensorflow/lite/micro/kernels/exp.o ./TFLM/tensorflow/lite/micro/kernels/exp.su ./TFLM/tensorflow/lite/micro/kernels/expand_dims.cyclo ./TFLM/tensorflow/lite/micro/kernels/expand_dims.d ./TFLM/tensorflow/lite/micro/kernels/expand_dims.o ./TFLM/tensorflow/lite/micro/kernels/expand_dims.su ./TFLM/tensorflow/lite/micro/kernels/fill.cyclo ./TFLM/tensorflow/lite/micro/kernels/fill.d ./TFLM/tensorflow/lite/micro/kernels/fill.o ./TFLM/tensorflow/lite/micro/kernels/fill.su ./TFLM/tensorflow/lite/micro/kernels/floor.cyclo ./TFLM/tensorflow/lite/micro/kernels/floor.d ./TFLM/tensorflow/lite/micro/kernels/floor.o ./TFLM/tensorflow/lite/micro/kernels/floor.su ./TFLM/tensorflow/lite/micro/kernels/floor_div.cyclo ./TFLM/tensorflow/lite/micro/kernels/floor_div.d ./TFLM/tensorflow/lite/micro/kernels/floor_div.o ./TFLM/tensorflow/lite/micro/kernels/floor_div.su ./TFLM/tensorflow/lite/micro/kernels/floor_mod.cyclo ./TFLM/tensorflow/lite/micro/kernels/floor_mod.d ./TFLM/tensorflow/lite/micro/kernels/floor_mod.o ./TFLM/tensorflow/lite/micro/kernels/floor_mod.su ./TFLM/tensorflow/lite/micro/kernels/fully_connected_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/fully_connected_common.d ./TFLM/tensorflow/lite/micro/kernels/fully_connected_common.o ./TFLM/tensorflow/lite/micro/kernels/fully_connected_common.su ./TFLM/tensorflow/lite/micro/kernels/gather.cyclo ./TFLM/tensorflow/lite/micro/kernels/gather.d ./TFLM/tensorflow/lite/micro/kernels/gather.o ./TFLM/tensorflow/lite/micro/kernels/gather.su ./TFLM/tensorflow/lite/micro/kernels/gather_nd.cyclo ./TFLM/tensorflow/lite/micro/kernels/gather_nd.d ./TFLM/tensorflow/lite/micro/kernels/gather_nd.o ./TFLM/tensorflow/lite/micro/kernels/gather_nd.su ./TFLM/tensorflow/lite/micro/kernels/hard_swish.cyclo ./TFLM/tensorflow/lite/micro/kernels/hard_swish.d ./TFLM/tensorflow/lite/micro/kernels/hard_swish.o ./TFLM/tensorflow/lite/micro/kernels/hard_swish.su ./TFLM/tensorflow/lite/micro/kernels/hard_swish_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/hard_swish_common.d ./TFLM/tensorflow/lite/micro/kernels/hard_swish_common.o ./TFLM/tensorflow/lite/micro/kernels/hard_swish_common.su ./TFLM/tensorflow/lite/micro/kernels/if.cyclo ./TFLM/tensorflow/lite/micro/kernels/if.d ./TFLM/tensorflow/lite/micro/kernels/if.o ./TFLM/tensorflow/lite/micro/kernels/if.su ./TFLM/tensorflow/lite/micro/kernels/kernel_runner.cyclo ./TFLM/tensorflow/lite/micro/kernels/kernel_runner.d ./TFLM/tensorflow/lite/micro/kernels/kernel_runner.o ./TFLM/tensorflow/lite/micro/kernels/kernel_runner.su ./TFLM/tensorflow/lite/micro/kernels/kernel_util.cyclo ./TFLM/tensorflow/lite/micro/kernels/kernel_util.d ./TFLM/tensorflow/lite/micro/kernels/kernel_util.o ./TFLM/tensorflow/lite/micro/kernels/kernel_util.su ./TFLM/tensorflow/lite/micro/kernels/l2_pool_2d.cyclo ./TFLM/tensorflow/lite/micro/kernels/l2_pool_2d.d ./TFLM/tensorflow/lite/micro/kernels/l2_pool_2d.o ./TFLM/tensorflow/lite/micro/kernels/l2_pool_2d.su ./TFLM/tensorflow/lite/micro/kernels/l2norm.cyclo ./TFLM/tensorflow/lite/micro/kernels/l2norm.d ./TFLM/tensorflow/lite/micro/kernels/l2norm.o ./TFLM/tensorflow/lite/micro/kernels/l2norm.su ./TFLM/tensorflow/lite/micro/kernels/leaky_relu.cyclo ./TFLM/tensorflow/lite/micro/kernels/leaky_relu.d ./TFLM/tensorflow/lite/micro/kernels/leaky_relu.o ./TFLM/tensorflow/lite/micro/kernels/leaky_relu.su ./TFLM/tensorflow/lite/micro/kernels/leaky_relu_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/leaky_relu_common.d ./TFLM/tensorflow/lite/micro/kernels/leaky_relu_common.o ./TFLM/tensorflow/lite/micro/kernels/leaky_relu_common.su ./TFLM/tensorflow/lite/micro/kernels/log_softmax.cyclo ./TFLM/tensorflow/lite/micro/kernels/log_softmax.d ./TFLM/tensorflow/lite/micro/kernels/log_softmax.o ./TFLM/tensorflow/lite/micro/kernels/log_softmax.su ./TFLM/tensorflow/lite/micro/kernels/logical.cyclo ./TFLM/tensorflow/lite/micro/kernels/logical.d ./TFLM/tensorflow/lite/micro/kernels/logical.o ./TFLM/tensorflow/lite/micro/kernels/logical.su ./TFLM/tensorflow/lite/micro/kernels/logical_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/logical_common.d ./TFLM/tensorflow/lite/micro/kernels/logical_common.o ./TFLM/tensorflow/lite/micro/kernels/logical_common.su ./TFLM/tensorflow/lite/micro/kernels/logistic.cyclo ./TFLM/tensorflow/lite/micro/kernels/logistic.d ./TFLM/tensorflow/lite/micro/kernels/logistic.o ./TFLM/tensorflow/lite/micro/kernels/logistic.su ./TFLM/tensorflow/lite/micro/kernels/logistic_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/logistic_common.d ./TFLM/tensorflow/lite/micro/kernels/logistic_common.o ./TFLM/tensorflow/lite/micro/kernels/logistic_common.su ./TFLM/tensorflow/lite/micro/kernels/lstm_eval.cyclo ./TFLM/tensorflow/lite/micro/kernels/lstm_eval.d ./TFLM/tensorflow/lite/micro/kernels/lstm_eval.o ./TFLM/tensorflow/lite/micro/kernels/lstm_eval.su ./TFLM/tensorflow/lite/micro/kernels/lstm_eval_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/lstm_eval_common.d ./TFLM/tensorflow/lite/micro/kernels/lstm_eval_common.o ./TFLM/tensorflow/lite/micro/kernels/lstm_eval_common.su ./TFLM/tensorflow/lite/micro/kernels/micro_tensor_utils.cyclo ./TFLM/tensorflow/lite/micro/kernels/micro_tensor_utils.d ./TFLM/tensorflow/lite/micro/kernels/micro_tensor_utils.o
	-$(RM) ./TFLM/tensorflow/lite/micro/kernels/micro_tensor_utils.su ./TFLM/tensorflow/lite/micro/kernels/mirror_pad.cyclo ./TFLM/tensorflow/lite/micro/kernels/mirror_pad.d ./TFLM/tensorflow/lite/micro/kernels/mirror_pad.o ./TFLM/tensorflow/lite/micro/kernels/mirror_pad.su ./TFLM/tensorflow/lite/micro/kernels/mul_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/mul_common.d ./TFLM/tensorflow/lite/micro/kernels/mul_common.o ./TFLM/tensorflow/lite/micro/kernels/mul_common.su ./TFLM/tensorflow/lite/micro/kernels/neg.cyclo ./TFLM/tensorflow/lite/micro/kernels/neg.d ./TFLM/tensorflow/lite/micro/kernels/neg.o ./TFLM/tensorflow/lite/micro/kernels/neg.su ./TFLM/tensorflow/lite/micro/kernels/pack.cyclo ./TFLM/tensorflow/lite/micro/kernels/pack.d ./TFLM/tensorflow/lite/micro/kernels/pack.o ./TFLM/tensorflow/lite/micro/kernels/pack.su ./TFLM/tensorflow/lite/micro/kernels/pad_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/pad_common.d ./TFLM/tensorflow/lite/micro/kernels/pad_common.o ./TFLM/tensorflow/lite/micro/kernels/pad_common.su ./TFLM/tensorflow/lite/micro/kernels/pooling_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/pooling_common.d ./TFLM/tensorflow/lite/micro/kernels/pooling_common.o ./TFLM/tensorflow/lite/micro/kernels/pooling_common.su ./TFLM/tensorflow/lite/micro/kernels/prelu.cyclo ./TFLM/tensorflow/lite/micro/kernels/prelu.d ./TFLM/tensorflow/lite/micro/kernels/prelu.o ./TFLM/tensorflow/lite/micro/kernels/prelu.su ./TFLM/tensorflow/lite/micro/kernels/prelu_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/prelu_common.d ./TFLM/tensorflow/lite/micro/kernels/prelu_common.o ./TFLM/tensorflow/lite/micro/kernels/prelu_common.su ./TFLM/tensorflow/lite/micro/kernels/quantize.cyclo ./TFLM/tensorflow/lite/micro/kernels/quantize.d ./TFLM/tensorflow/lite/micro/kernels/quantize.o ./TFLM/tensorflow/lite/micro/kernels/quantize.su ./TFLM/tensorflow/lite/micro/kernels/quantize_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/quantize_common.d ./TFLM/tensorflow/lite/micro/kernels/quantize_common.o ./TFLM/tensorflow/lite/micro/kernels/quantize_common.su ./TFLM/tensorflow/lite/micro/kernels/read_variable.cyclo ./TFLM/tensorflow/lite/micro/kernels/read_variable.d ./TFLM/tensorflow/lite/micro/kernels/read_variable.o ./TFLM/tensorflow/lite/micro/kernels/read_variable.su ./TFLM/tensorflow/lite/micro/kernels/reduce.cyclo ./TFLM/tensorflow/lite/micro/kernels/reduce.d ./TFLM/tensorflow/lite/micro/kernels/reduce.o ./TFLM/tensorflow/lite/micro/kernels/reduce.su ./TFLM/tensorflow/lite/micro/kernels/reduce_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/reduce_common.d ./TFLM/tensorflow/lite/micro/kernels/reduce_common.o ./TFLM/tensorflow/lite/micro/kernels/reduce_common.su ./TFLM/tensorflow/lite/micro/kernels/reshape.cyclo ./TFLM/tensorflow/lite/micro/kernels/reshape.d ./TFLM/tensorflow/lite/micro/kernels/reshape.o ./TFLM/tensorflow/lite/micro/kernels/reshape.su ./TFLM/tensorflow/lite/micro/kernels/reshape_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/reshape_common.d ./TFLM/tensorflow/lite/micro/kernels/reshape_common.o ./TFLM/tensorflow/lite/micro/kernels/reshape_common.su ./TFLM/tensorflow/lite/micro/kernels/resize_bilinear.cyclo ./TFLM/tensorflow/lite/micro/kernels/resize_bilinear.d ./TFLM/tensorflow/lite/micro/kernels/resize_bilinear.o ./TFLM/tensorflow/lite/micro/kernels/resize_bilinear.su ./TFLM/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cyclo ./TFLM/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d ./TFLM/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o ./TFLM/tensorflow/lite/micro/kernels/resize_nearest_neighbor.su ./TFLM/tensorflow/lite/micro/kernels/round.cyclo ./TFLM/tensorflow/lite/micro/kernels/round.d ./TFLM/tensorflow/lite/micro/kernels/round.o ./TFLM/tensorflow/lite/micro/kernels/round.su ./TFLM/tensorflow/lite/micro/kernels/select.cyclo ./TFLM/tensorflow/lite/micro/kernels/select.d ./TFLM/tensorflow/lite/micro/kernels/select.o ./TFLM/tensorflow/lite/micro/kernels/select.su ./TFLM/tensorflow/lite/micro/kernels/shape.cyclo ./TFLM/tensorflow/lite/micro/kernels/shape.d ./TFLM/tensorflow/lite/micro/kernels/shape.o ./TFLM/tensorflow/lite/micro/kernels/shape.su ./TFLM/tensorflow/lite/micro/kernels/slice.cyclo ./TFLM/tensorflow/lite/micro/kernels/slice.d ./TFLM/tensorflow/lite/micro/kernels/slice.o ./TFLM/tensorflow/lite/micro/kernels/slice.su ./TFLM/tensorflow/lite/micro/kernels/softmax_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/softmax_common.d ./TFLM/tensorflow/lite/micro/kernels/softmax_common.o ./TFLM/tensorflow/lite/micro/kernels/softmax_common.su ./TFLM/tensorflow/lite/micro/kernels/space_to_batch_nd.cyclo ./TFLM/tensorflow/lite/micro/kernels/space_to_batch_nd.d ./TFLM/tensorflow/lite/micro/kernels/space_to_batch_nd.o ./TFLM/tensorflow/lite/micro/kernels/space_to_batch_nd.su ./TFLM/tensorflow/lite/micro/kernels/space_to_depth.cyclo ./TFLM/tensorflow/lite/micro/kernels/space_to_depth.d ./TFLM/tensorflow/lite/micro/kernels/space_to_depth.o ./TFLM/tensorflow/lite/micro/kernels/space_to_depth.su ./TFLM/tensorflow/lite/micro/kernels/split.cyclo ./TFLM/tensorflow/lite/micro/kernels/split.d ./TFLM/tensorflow/lite/micro/kernels/split.o ./TFLM/tensorflow/lite/micro/kernels/split.su ./TFLM/tensorflow/lite/micro/kernels/split_v.cyclo ./TFLM/tensorflow/lite/micro/kernels/split_v.d ./TFLM/tensorflow/lite/micro/kernels/split_v.o ./TFLM/tensorflow/lite/micro/kernels/split_v.su ./TFLM/tensorflow/lite/micro/kernels/squared_difference.cyclo ./TFLM/tensorflow/lite/micro/kernels/squared_difference.d ./TFLM/tensorflow/lite/micro/kernels/squared_difference.o ./TFLM/tensorflow/lite/micro/kernels/squared_difference.su ./TFLM/tensorflow/lite/micro/kernels/squeeze.cyclo ./TFLM/tensorflow/lite/micro/kernels/squeeze.d ./TFLM/tensorflow/lite/micro/kernels/squeeze.o ./TFLM/tensorflow/lite/micro/kernels/squeeze.su ./TFLM/tensorflow/lite/micro/kernels/strided_slice.cyclo ./TFLM/tensorflow/lite/micro/kernels/strided_slice.d ./TFLM/tensorflow/lite/micro/kernels/strided_slice.o
	-$(RM) ./TFLM/tensorflow/lite/micro/kernels/strided_slice.su ./TFLM/tensorflow/lite/micro/kernels/strided_slice_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/strided_slice_common.d ./TFLM/tensorflow/lite/micro/kernels/strided_slice_common.o ./TFLM/tensorflow/lite/micro/kernels/strided_slice_common.su ./TFLM/tensorflow/lite/micro/kernels/sub.cyclo ./TFLM/tensorflow/lite/micro/kernels/sub.d ./TFLM/tensorflow/lite/micro/kernels/sub.o ./TFLM/tensorflow/lite/micro/kernels/sub.su ./TFLM/tensorflow/lite/micro/kernels/sub_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/sub_common.d ./TFLM/tensorflow/lite/micro/kernels/sub_common.o ./TFLM/tensorflow/lite/micro/kernels/sub_common.su ./TFLM/tensorflow/lite/micro/kernels/svdf_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/svdf_common.d ./TFLM/tensorflow/lite/micro/kernels/svdf_common.o ./TFLM/tensorflow/lite/micro/kernels/svdf_common.su ./TFLM/tensorflow/lite/micro/kernels/tanh.cyclo ./TFLM/tensorflow/lite/micro/kernels/tanh.d ./TFLM/tensorflow/lite/micro/kernels/tanh.o ./TFLM/tensorflow/lite/micro/kernels/tanh.su ./TFLM/tensorflow/lite/micro/kernels/transpose_common.cyclo ./TFLM/tensorflow/lite/micro/kernels/transpose_common.d ./TFLM/tensorflow/lite/micro/kernels/transpose_common.o ./TFLM/tensorflow/lite/micro/kernels/transpose_common.su ./TFLM/tensorflow/lite/micro/kernels/unpack.cyclo ./TFLM/tensorflow/lite/micro/kernels/unpack.d ./TFLM/tensorflow/lite/micro/kernels/unpack.o ./TFLM/tensorflow/lite/micro/kernels/unpack.su ./TFLM/tensorflow/lite/micro/kernels/var_handle.cyclo ./TFLM/tensorflow/lite/micro/kernels/var_handle.d ./TFLM/tensorflow/lite/micro/kernels/var_handle.o ./TFLM/tensorflow/lite/micro/kernels/var_handle.su ./TFLM/tensorflow/lite/micro/kernels/while.cyclo ./TFLM/tensorflow/lite/micro/kernels/while.d ./TFLM/tensorflow/lite/micro/kernels/while.o ./TFLM/tensorflow/lite/micro/kernels/while.su ./TFLM/tensorflow/lite/micro/kernels/zeros_like.cyclo ./TFLM/tensorflow/lite/micro/kernels/zeros_like.d ./TFLM/tensorflow/lite/micro/kernels/zeros_like.o ./TFLM/tensorflow/lite/micro/kernels/zeros_like.su

.PHONY: clean-TFLM-2f-tensorflow-2f-lite-2f-micro-2f-kernels

